### PR TITLE
beta: Update runtime to GNOME 45

### LINKED ISSUE #251: Update beta to GNOME 45
Update beta to GNOME 45

This is currently blocked by this:

https://gitlab.gnome.org/GNOME/gnome-build-meta/-/issues/736

tl;dr GIMP link against libappstream-glib but it is removed in the platform while still in the SDK.

### PR DESCRIPTION
**Pull request by hfiguiere**
- added appstream-glib in because it's missing from the platform

Close #251

### CODE REVIEW

**Comment by hfiguiere** [comment]
freedesktop issue it seems.

bot, build

**Comment by hfiguiere** [comment]
the error is in the checker rule. The tarball name is WRONG.

**Comment by hfiguiere** [comment]
removed the f-e-d-c stanza, it's broken.

**Comment by Jehan** [comment]
> removed the f-e-d-c stanza, it's broken.

f-e-d-c? It looks like you mean the "x-checker-data" part (no idea what f-e-d-c means).

Isn't it possible to just fix the URL template or something if it's wrong? This whole automatic check thing is really really practical (despite the annoying duplicate MRs, it still helps us a lot to keep dependencies up-to-date).

**Comment by hfiguiere** [comment]
> > removed the f-e-d-c stanza, it's broken.
> 
> f-e-d-c? It looks like you mean the "x-checker-data" part (no idea what f-e-d-c means).

flatpak-external-data-checker,

 
> Isn't it possible to just fix the URL template or something if it's wrong? This whole automatic check thing is really really practical (despite the annoying duplicate MRs, it still helps us a lot to keep dependencies up-to-date).

appstream-glib is dead anyway.

I have looked at the code and I don't see any easy to fix it. The version output by Anitya is x_y_z. So there is no `${version1}`, etc

Personally I have a much less favourable view of f-e-d-c. Exhibit 1.

**Comment by hfiguiere** [comment]
shall we merge this?

**Comment by Jehan** [comment]
> shall we merge this?

Sure! I'd prefer for the version checker string to be present, but we can always try to fix it afterwards. @HarryMichal can probably help on this!

> Personally I have a much less favourable view of f-e-d-c. Exhibit 1.

Well it may not be perfect, and the duplicate MRs are also small bothers. But so far, it was extremely useful and helpful, so much that the little issues are perfectly acceptable to me. Anyway which software is perfect? 😅

Personally I really appreciate this version checker system.

Anyway feel very free to take some initiative. A runtime update is definitely a good thing, so as long as you confirmed it works fine with the fix and that you tested it, I'm very fine with you merging such fixes.

My ultimate goal is for me to have to do as less as possible in packaging tasks! 😜

So yeah, just merge if it works fine after the update.

**Comment by hfiguiere** [comment]
A runtime update will remove the need to build appstream glib

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/15691

My take is that GIMP shouldn't depend on this for runtime. At best at build time. Also it's currently unmaintained and about to be deprecated.

As for f-e-d-c, I couldn't find a way to make it work. IMHO the whole thing needs fixing.

**Comment by Jehan** [comment]
> A runtime update will remove the need to build appstream glib

So after runtime 45? Like 46 or something?

In the meantime, don't you want to merge this MR?

> My take is that GIMP shouldn't depend on this for runtime. At best at build time.

It's a runtime dependency. We use the AppStream format as our metadata format for extensions (a new wrapper format to various types of extensions, like plug-ins, brushes, themes and whatnot). This needs to be read at runtime to display list of installed extensions, or installable extensions, etc. (i.e. like installing plug-ins in Firefox, where you have plug-in screenshots, descriptions and more metadata).

> Also it's currently unmaintained and about to be deprecated.

Sure. We need to move on to libappstream. I've heard about this coming deprecation. We'll do this eventually. It's not the first time we change underlying dependencies and it won't be the last. But for the time being, it's what it is and updating this is not my priority for GIMP 3. ;-)

**Comment by hfiguiere** [comment]
> > A runtime update will remove the need to build appstream glib
> 
> So after runtime 45? Like 46 or something?

23.08 update, so 45 too.

> In the meantime, don't you want to merge this MR?

Sure I do.

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
Removed Cairo since that version is in the runtime and make f-e-d-c choke because the URL is incorrect.

**Comment by HarryMichal** [comment]
> As for f-e-d-c, I couldn't find a way to make it work. IMHO the whole thing needs fixing.

The tool is certainly quirky and to save myself some energy I just ended up using it using Podman/Docker. Making it run in a manually set up environment would be too much of a hassle.

Also, I'd like express how much I value you (both of you actually) keeping the lights on around here. Life has happened and I am not able to volunteer in the open source world as much as I did and as I'd like to. And also with all that additional cruft around generated by the dependency updater tool.

**Comment by Jehan** [comment]
@HarryMichal No problem. I hope you'll get some more time soon (for FLOSS or just to enjoy it!). :-)

In any case, you are always welcome here to continue contributing whenever you want and if you find the time. Your permissions stay anyway. ;-)

**Pull request merged**
