### PR TITLE
Issue #121 - Update runtime to GNOME 41

### LINKED ISSUE #121: Update to org.gnome.Platform runtime version 41

### PR DESCRIPTION
**Pull request by hfiguiere**
- added patch to build WebKit

Close #121

### CODE REVIEW

**Comment by hfiguiere** [comment]
libwmf fail to build because it still use the deprecated freetype2 detection.

(I didn't even reach this as webkit fails here)

**Comment by hfiguiere** [comment]
patch submitted upstream https://github.com/caolanm/libwmf/pull/7

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
Added another patch and run autoreconf for libwmf.

**Comment by hfiguiere** [comment]
we need to rebuild GMIC because of icu, the others are ok.

**Comment by hfiguiere** [comment]
Back to draft (to prevent merging)
I need to fix the GMic build first...

**Comment by hfiguiere** [comment]
Ok, https://github.com/flathub/org.gimp.GIMP.Plugin.GMic/pull/20 needs to be merged when this is merged.

**Comment by Jehan** [comment]
Well done as always @hfiguiere.
I let you take the lead here. Merge whenever you want. 🙂

**Pull request merged**
