### PR TITLE
Use app-id not id in the manifest

### PR DESCRIPTION
**Pull request by supertobi**
According to the documentation we should use "app-id" and not "id" in the manifest:
http://docs.flatpak.org/en/latest/manifests.html

### CODE REVIEW

**Comment by Jehan** [comment]
Did this change recently? I'm pretty sure that used to be just "id".

**Comment by barthalion** [comment]
Both are correct.

**Comment by Jehan** [comment]
@barthalion Ok. And is one "more correct" than the other? Specifically is "id" still accepted as alias yet deprecated and changing to "app-id" is actually the way forward?

**Comment by barthalion** [comment]
`app-id` is certainly more widely used. Probably both are supposed to make things easier for newcomers.

**Comment by Jehan** [comment]
Ok. Let's merge this then, especially if the doc now writes down to use this one instead.

**Pull request merged**
