### PR TITLE
Prepare 2.99.18 release.

### PR DESCRIPTION
**Pull request by Jehan**

### CODE REVIEW

**Comment by hfiguiere** [comment]
Exception to the linter https://github.com/flathub-infra/flatpak-builder-lint/pull/284

So we can rebuild in a bit.

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
it passed the linter.

**Comment by Jehan** [comment]
Thanks @hfiguiere !

**Comment by hfiguiere** [comment]
new linter rules got pushed as we are trying to move away from some deprecated tooling.

:-(

**Comment by hfiguiere** [comment]
I built it locally with all the tools and it passed.

bot, build

**Comment by Jehan** [comment]
Validation fails with this, but the error "appstream-failed-validation" is very obscure.

```
{
    "errors": [
        "appstream-failed-validation"
    ],
    "warnings": [
        "appstream-name-too-long"
    ],
    "appstream": [
        "I: org.gimp.GIMP:12: developer-name-tag-deprecated",
        "I: org.gimp.GIMP:28: developer-name-tag-deprecated",
        "I: org.gimp.GIMP:26: developer-name-tag-deprecated",
        "I: org.gimp.GIMP:17: developer-name-tag-deprecated",
        "I: org.gimp.GIMP:22: developer-name-tag-deprecated",
        "I: org.gimp.GIMP:9: developer-name-tag-deprecated",
        "I: org.gimp.GIMP:21: developer-name-tag-deprecated",
        "I: org.gimp.GIMP:420: nonstandard-gnome-extension kudos",
        "I: org.gimp.GIMP:25: developer-name-tag-deprecated",
        "I: org.gimp.GIMP:27: developer-name-tag-deprecated",
        "I: org.gimp.GIMP:18: developer-name-tag-deprecated",
        "I: org.gimp.GIMP:14: developer-name-tag-deprecated",
        "I: org.gimp.GIMP:23: developer-name-tag-deprecated",
        "I: org.gimp.GIMP:29: developer-name-tag-deprecated",
        "I: org.gimp.GIMP:19: developer-name-tag-deprecated",
        "I: org.gimp.GIMP:20: developer-name-tag-deprecated",
        "I: org.gimp.GIMP:11: developer-name-tag-deprecated",
        "W: org.gimp.GIMP:432: tag-empty id",
        "I: org.gimp.GIMP:7: developer-name-tag-deprecated",
        "I: org.gimp.GIMP:8: developer-name-tag-deprecated",
        "I: org.gimp.GIMP:15: developer-name-tag-deprecated",
        "I: org.gimp.GIMP:31: developer-name-tag-deprecated",
        "I: org.gimp.GIMP:10: developer-name-tag-deprecated",
        "I: org.gimp.GIMP:24: developer-name-tag-deprecated",
        "I: org.gimp.GIMP:30: developer-name-tag-deprecated",
        "I: org.gimp.GIMP:13: developer-name-tag-deprecated",
        "I: org.gimp.GIMP:16: developer-name-tag-deprecated"
    ],
    "message": "Please consult the documentation at https://docs.flathub.org/docs/for-app-authors/linter"
}
```

**Comment by hfiguiere** [comment]
I'm waiting for the latest build of flatpak-builder to retrigger. The `W:` line is caused by a bug in the tooling (and cause the error)

**Comment by hfiguiere** [comment]
bot, build

**Comment by Jehan** [comment]
Now the error in AppStream validation is:

```
{
    "errors": [
        "appstream-failed-validation"
    ],
    "warnings": [
        "appstream-name-too-long"
    ],
    "appstream": [
        "Can not override issue tag: It is not allowed to downgrade the severity of tag 'console-app-no-binary' to one that allows validation to pass."
    ],
    "message": "Please consult the documentation at https://docs.flathub.org/docs/for-app-authors/linter"
}
```

I assume `console-app-no-binary` is the problem. Searching linter code, I see 2 recent commits about it: https://github.com/flathub-infra/flatpak-builder-lint/commit/3e2cc79278253d0ee09364ecc900ab5fe39cb220 and https://github.com/flathub-infra/flatpak-builder-lint/commit/1b50f6ae60b7913763dc30dad540d1d0f2d38e69

Let's hope it's enough.

bot, build

**Pull request merged**
