### PR TITLE
[beta] Update to GNOME 42

### LINKED ISSUE #140: Please update the runtime for the beta channel
Title says it all: The beta channel is still on the GNOME 40 runtime (while stable is on 41) which is getting awfully close to being EOL'd.

### PR DESCRIPTION
**Pull request by hfiguiere**
- close #140

### CODE REVIEW

**Comment by hfiguiere** [comment]
let's test this first.

**Comment by hfiguiere** [comment]
The build work be we need to wait that I fix the GMIC build.

**Comment by hfiguiere** [comment]
seems to be working including with a new GMIC build

**Comment by Jehan** [comment]
Taking the opportunity to make some updates, at least for babl which had a recent release. :-)

**Comment by hfiguiere** [comment]
So shall we merge this? The GMIC plugin is ready too.

**Comment by Jehan** [comment]
I do see in the build (thanks to the new version check stuff by @HarryMichal that there are a bunch of outdated dependencies:

```
CHANGE SOON: lcms2-2.12.tar.gz
 Has a new version:
  URL:       https://github.com/mm2/Little-CMS/releases/download/lcms2.13.1/lcms2-2.13.1.tar.gz
  MD5:       47a99e781b89c958a773e2012e81ae8c
  SHA1:      72d0a0b7fbaeca12eb0186ab5728eb0f26806b22
  SHA256:    d473e796e7b27c5af01bd6d1552d42b45b43457e7182ce9903f38bb748203b88
  SHA512:    214ec63fa086b580a6507d493a54ccf5faf02c40e149d71e41f9fc8510efdb16554621c96d91cc886f09682c9631b10aa194b4b67eb6ffcc871d5d4666b05617
  Size:      7276499
  Version:   2.13.1
  Timestamp: 2022-02-03 13:25:42

CHANGE SOON: poppler-22.01.0.tar.xz
 Has a new version:
  URL:       https://poppler.freedesktop.org/poppler-22.03.0.tar.xz
  MD5:       4056aa01aff289d54119bb506b8b75e7
  SHA1:      8954e0c096da0a9d12797f04668926647650fe0e
  SHA256:    728c78ba94d75a55f6b6355d4fbdaa6f49934d9616be58e5e679a9cfd0980e1e
  SHA512:    f87bbff4f394f192095da0c00bdf8b5c70b7eb864941225aad2025e91283c3c42a0016a772e7e9ea73a86746251928fc64500f923e8fd841adae1c6e67d72569
  Size:      1809940
  Version:   22.03.0
  Timestamp: 2022-03-24 16:59:16

CHANGE SOON: v0.3.19.tar.gz
 Has a new version:
  URL:       https://github.com/xianyi/OpenBLAS/archive/v0.3.20.tar.gz
  MD5:       abfaa43d995046ca4c56ccf14165c93c
  SHA1:      45ec54b75f53f5b704250e60bd8e82a49b430619
  SHA256:    8495c9affc536253648e942908e88e097f2ec7753ede55aca52e5dead3029e3c
  SHA512:    0742d40b74b11b781021280fd627fa5798e6856b49f2ba1111a5927aac1a7823bcb8162187555f4cf3a4dd7eadf5b1f2a4685c0b5e189847b2869166d1bc7391
  Size:      12742441
  Version:   0.3.20
  Timestamp: 2022-03-25 10:30:00

CHANGE SOON: v5.10.1.tar.gz
 Has a new version:
  URL:       https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/v5.11.0.tar.gz
  MD5:       909a75e6abca32a329a593a96dc00de7
  SHA1:      fe226ba60278ac0d7b09a35129b3ca4d65fcf682
  SHA256:    fdd957ed06019465f7de73ce931afaf5d40e96e14ae57d91f60868b8c123c4c8
  SHA512:    242915b1771ae6230831fcbb5fe80bcc14cbf701d0901ff4565a00de9e3e93ba4383d76f916445fdb62ba09e405cc7c45951ac0da3796f5b4be1187e1cc24ee3
  Size:      64555786
  Version:   5.11.0
  Timestamp: 2022-03-25 10:30:00

CHANGE SOON: cairo-1.17.4.tar.gz
 Has a new version:
  URL:       https://gitlab.freedesktop.org/cairo/cairo/-/archive/1.17.6/cairo-1.17.6.tar.gz
  MD5:       bbea11bcc63e465e58aa054b56350b04
  SHA1:      3e457325e036224ca47f5b566e9e4892651473f2
  SHA256:    a2227afc15e616657341c42af9830c937c3a6bfa63661074eabef13600e8936f
  SHA512:    fc47364622cf988fed86031af6c4ce2d7454de003d4daf97d7d1c987f27960b9026a3b07815a059dcecc3a2a8b79cc7d837e7d95ea0f172cbda63034160f85fb
  Size:      48653536
  Version:   1.17.6
  Timestamp: 2022-03-25 10:30:00

CHANGE SOON: graphviz-2.50.0.tar.gz
 Has a new version:
  URL:       https://gitlab.com/graphviz/graphviz/-/archive/3.0.0/graphviz-3.0.0.tar.gz
  MD5:       ed5274f23edebca2dd7d48f87c94ce97
  SHA1:      1822db1086c7b64f2cccc06b5811cde1914be71c
  SHA256:    59931082a3638139e06c296b96e860a9d338432af06f7f57a6ad8da5cbf465c7
  SHA512:    5c95a867e155bafbbf9e4c021544ccd26eca6d9cc3eb97f854c78ef0ba1821a351739293a14436bc3d07cc07774b65571b5d5bb176bd31b3de672de0a8aa6100
  Size:      30563878
  Version:   3.0.0
  Timestamp: 2022-03-25 10:30:00
```

I can't make the time to update these now but if @HarryMichal or yourself can test-push to the branch, would be nice.

Otherwise, sure just pushing as-is is good too, of course. :-)

**Comment by hfiguiere** [comment]
I'll merge this as it needs coordination for the GMIC plugin (runtime change, Qt doesn't like it)

The other dependencies can be updated later.

**Comment by hfiguiere** [comment]
btw the cairo update might be breaking (not sure I have had issue with Inkscape) so is possibly the graphviz version bump. So it might require a bit of work.

**Comment by hfiguiere** [comment]
The build is delayed due to GNOME infra issues to fetch sources, I'll monitor and retrigger.

**Comment by Jehan** [comment]
Sure. Thanks!

**Comment by HarryMichal** [comment]
Will go through the updates.

**Pull request merged**
