### PR TITLE
Update to runtime 3.32.

### PR DESCRIPTION
**Pull request by Jehan**
Hopefully just bumping the runtime version is enough.

### CODE REVIEW

**Comment by Erick555** [comment]
Smooth as silk 😄

**Comment by Erick555** [comment]
@Jehan is anything blocking this one?

**Comment by Jehan** [comment]
@Erick555 Not really. I was just wondering if there were no more commits I wanted to add first. Problem is that every merge results in an update of the released binaries, which means dozens of thousands of downloads for basically no perceivable changes (here the runtime update changes nothing for people, no bug fix, no features, nothing). It just feels counter-productive.

So I prefer to bundle together various changes so that at least, the update is not completely meaningless. Therefore I'll sit a bit on this one for now. It will go in, of course, no problems. There is just no hurry. :-)

**Comment by Erick555** [comment]
That's reasonable however with ostree deduplication the download size of update with no changes should be pretty minimal.

**Comment by palvarez89** [comment]
Upgrading it would mean that I can uninstall `org.gnome.Platform/x86_64/3.30` :)

**Comment by Jehan** [comment]
Ok let's merge this one! I added some patches to our GTK+ so that this update at least makes some improvements from the vanilla GTK+2 (since we have a few patches of our own which get never included; doesn't look like GTK+2 is much maintained anymore these days).

**Comment by palvarez89** [comment]
Just as a side note: This update took around 5 seconds on my laptop :)

Thanks for updating it!

**Pull request merged**
