### PR TITLE
Release GIMP 2.99.12

### PR DESCRIPTION
**Pull request by Jehan**
Release preparation branch.

### CODE REVIEW

**Comment by Jehan** [comment]
bot, build

**Comment by HarryMichal** [comment]
Thank you for taking care of this, @Jehan!

**Comment by Jehan** [comment]
Sure. If you want to handle next releases for the flatpak, feel free @HarryMichal. I'm more than happy to delegate, as I have so much on my hands. I even did a mistake on this flathub release and quickly pushed an additional commit e29690924661d94a77e58d138f273d40bfcbe184 to fix it! 😱

If you follow a bit the [milestone](https://gitlab.gnome.org/GNOME/gimp/-/milestones) section on the Gitlab, you can see planned release date. Or ideally if you hang our on IRC with us, we announce and discuss these. Otherwise, maybe we can make a procedure where I make a report to announce a planned release so that anyone of us can start preparing a release.

**Comment by HarryMichal** [comment]
I'll be happy to help out next time! The milestones seem like a nice way to keep track of the release date. And I can also join the IRC channel.

**Comment by Jehan** [comment]
> And I can also join the IRC channel.

Just in case you don't know/remember, our IRC channel is `#gimp` on irc.gimp.org. We are usually around daily.

There is no obligation to talk. You can just stay around and check from time to time if someone mentions you (if your nickname is different on IRC, say hello once at least so that we see who is who) or say things when you need or want to say something. Though you are also welcome to chitchat sometimes if you wish too (everyone their own character!).
It's pretty chill basically. :-)

P.S.: my own nick on IRC is the same as here.

**Pull request merged**
