### PR TITLE
Update SDK to 3.34

### LINKED ISSUE #60: Update runtime to 3.34

### PR DESCRIPTION
**Pull request by hfiguiere**
-Tweak dependencies
-Use https for downloads
-Patch pygtk

Closes #60, Closes #61

### CODE REVIEW

**Comment by Jehan** [comment]
At a quick glance, looks very fine, thanks!

Let me review this more closely this week-end, and I'll likely merge.

**Comment by Erick555** [comment]
@hfiguiere I recommend bumping ibus-gtk2 to 1.5.20 in order to match gtk3 version in runtime. Historically mismatches between those caused issues.

**Comment by hfiguiere** [comment]
I bumped ibus to the recommended version. Build passed.

**Comment by Jehan** [comment]
All very good. Thanks! Keep the patches coming everyone. :-)

**Pull request merged**
