### PR TITLE
Update runtime to GNOME 46

### LINKED ISSUE #273: Update runtime to 45
Consider updating the runtime version used by this Flatpak to 45.

### PR DESCRIPTION
**Pull request by hfiguiere**
Close #273

### CODE REVIEW

**Comment by hfiguiere** [comment]
let's try 45. The thing is 44 will be EOL soon.

**Comment by hfiguiere** [comment]
I forgot 45 is the same runtime as 46: 23.08

**Comment by hfiguiere** [comment]
This works, but I need to rebuild GMIC first. And we can get them merged at the same time.

**Comment by hfiguiere** [comment]
see https://github.com/flathub/org.gimp.GIMP.Plugin.GMic/pull/59

**Comment by hfiguiere** [comment]
@Jehan let me know if you are ok with this

**Comment by hfiguiere** [comment]
44 will be EOL in a couple of weeks

**Comment by Jehan** [comment]
> @Jehan let me know if you are ok with this

@hfiguiere Updating runtimes and dependencies is basic maintenance. I'm always OK with it and I'm fully trusting you on it considering your experience doing this.

Just go ahead if you tested and all seems to work fine.

P.S.: the less I have to do, the better I feel because I already do too much stuff. So I am more than happy entrusting you with such things. ;-)

**Pull request merged**
