### PR TITLE
Update runtime to gnome 42

### PR DESCRIPTION
**Pull request by FakeShemp**

### CODE REVIEW

**Comment by hfiguiere** [comment]
no. this require coordination for the plugins, notably GMic.

**Comment by Jehan** [comment]
@FakeShemp I don't think @hfiguiere meant this needed to be closed. But this could not be merged just like this, on a whim (i.e. it "requires coordination"). So it's good but we just won't merge it right now. Maybe later.

Right @hfiguiere ? Let's reopen this and you can merge it when you see fit, i.e. once the plug-ins are ready too?

**Comment by hfiguiere** [comment]
yes we can coordinate

**Comment by Jehan** [comment]
Open let's reopen. Then @hfiguiere just take your time. Nobody will merge this until it's good on plug-in side. 👍

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
the plugins already work with 42 as it is the same freedesktop-sdk.

So we should be ok to merge whenever.

**Comment by Jehan** [comment]
@hfiguiere Feel free to update when you are happy with the change. :-)

**Pull request merged**
