### PR TITLE
Preparing GIMP 3.0.0 RC1 release

### LINKED ISSUE #334: Update beta flatpak to Gnome 46
For what it's worth Inkscape is on org.gnome.Platform//46.
Thanks for all you do; onward to 3.0!

### PR DESCRIPTION
**Pull request by Jehan**
Closes #334

We are not releasing immediately, but I wanted to start testing some permission change before making a decision on whether to drop it completely or use the updated flag.

### CODE REVIEW

**Comment by Jehan** [comment]
bot, build

**Comment by brunvonlope** [comment]
bot, build

**Comment by brunvonlope** [comment]
bot, build

**Comment by brunvonlope** [comment]
@hfiguiere Build is succeeding but I get HTTP 401 error

**Comment by hfiguiere** [comment]
build infra is borked. admins have been paged. Just have patience.

**Comment by brunvonlope** [comment]
bot, build

**Comment by brunvonlope** [comment]
Just to clarify. This last commit (https://github.com/flathub/org.gimp.GIMP/pull/287/commits/3241f4f597006d9a8c243c4b2b72e628756e00aa) is almost optional here because we have flathub bot working quite well. But the manifest willn't work locally.

**Comment by Jehan** [comment]
Now it fails when pulling GIMP sources with:

```
Fetching full git repo https://gitlab.gnome.org/GNOME/gimp.git
FB: Running: git fetch -f -p --no-recurse-submodules --tags origin '*:*'
error: RPC failed; HTTP 504 curl 22 The requested URL returned error: 504
fatal: expected 'packfile'
Failed to download sources: module gimp: Child process exited with code 128
```

@hfiguiere  I assume that Flathub infra is still borked since our repo is accessible right now? 😢

**Comment by brunvonlope** [comment]
@Jehan Almost sure that this is GNOME Infra problem. That happened a lot of times in my unrelated windows builds on CI.

**Comment by Jehan** [comment]
bot, build

**Comment by Jehan** [comment]
bot, build

**Comment by Jehan** [comment]
bot, build

**Comment by Jehan** [comment]
@hfiguiere [Status page](https://status.flathub.org/) indicates that it's all good and the test build did indeed succeed. But for the main build, on the main [buildbot page](https://buildbot.flathub.org/), I don't it neither in "Current builds" nor in Unpublished or Recent builds.

Do we have to start builds manually now? Is there some delay on the infra maybe, which the bot is slowly trying to catch up to? Thanks!

**Comment by hfiguiere** [comment]
there is a lot of catchup.

**Comment by Jehan** [comment]
Ok. That's what I thought. Thanks @hfiguiere.

**Pull request merged**
