### PR TITLE
Add extension point

### PR DESCRIPTION
**Pull request by FakeShemp**
Add an extension point so that we can start to build plugins for GIMP.

Discussion about it in https://github.com/flathub/org.gimp.GIMP/issues/10 and https://github.com/flathub/org.gimp.GIMP/issues/22.

### CODE REVIEW

**Comment by Jehan** [comment]
Very nice . Has it been tested with actual plug-ins? If so could you post here the example manifest to document what should a plug-in manifest look like?

Le 3 août 2019 17:17:38 GMT+02:00, Flathub Bot <notifications@github.com> a écrit :
>Build [6137
>successful](https://flathub.org/builds/#/builders/32/builds/6137)
>To test this build, install it from the testing repository:
>```
>flatpak install --user
>https://dl.flathub.org/build-repo/5879/org.gimp.GIMP.flatpakref
>```
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/flathub/org.gimp.GIMP/pull/59#issuecomment-517932175

-- 
ZeMarmot: https://film.zemarmot.net

**Comment by FakeShemp** [comment]
I'm working on adding a plugin but haven't finished yet.

**Comment by FakeShemp** [comment]
bot, build

**Comment by FakeShemp** [comment]
bot, build

**Comment by Jehan** [comment]
Hi! What is the status of this patch? :-)

Last we heard, you were testing if it actually worked. Did your test succeed?

**Comment by hfiguiere** [comment]
If you don't mind I'll take over this. I'll submit a new PR based on this, but tested and a few plugins. (Resynthesizer just got tested)

**Comment by FakeShemp** [comment]
Yes please. I never got it to work myself.

**Pull request closed without merging**
